name: Terraform plan
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: Manual trigger
        default: destroy
        required: true
        type: choice
        options:
            - plan
            - apply
            - destroy
env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
  TF_VERSION: "1.14.3" 

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-north-1"

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Terraform init, validate, plan
        run: |
          terraform init
          terraform validate
          terraform plan -input=false -out=tfplan

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: tfplan
          path: tfplan

  apply:
    if: inputs.action == 'apply'
    needs: plan
    runs-on: ubuntu-latest
    environment: apply-approval
    steps:
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Download tfplan artifact
        uses: actions/download-artifact@v5
        with:
          name: tfplan
          path: .

      - name: TF apply
        run: |
          terraform init -input=false
          terraform apply -auto-approve tfplan

  destroy:
    if: inputs.action == 'destroy'
    runs-on: ubuntu-latest
    environment: destroy-approval
    steps:
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-north-1"

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Terraform destroy
        run: |
          terraform init -input=false
          terraform destroy -auto-approve



      


    
    